Updated data_module.py
Fix a bug of "TypeError: __init__() missing 1 required positional argument: 'logits_files'". Changed logit_files to logits_files in line 130.